# Generated by Django 4.2.3 on 2023-07-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('current_state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('detection_id', models.IntegerField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=255)),
                ('detected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('localization', models.CharField(max_length=255)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.currentstate')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('metadata_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_count', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hologram_position', models.CharField(max_length=255)),
                ('arrow_position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('qrcode', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assistent_remote', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tutorial', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('work_station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('qrcode', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.detection')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.metadata')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.position')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.priority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='work_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.workstation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.role'),
        ),
    ]
