# Generated by Django 4.2.3 on 2023-07-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_currentstate_detection_employee_metadata_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
