# Generated by Django 4.2.3 on 2023-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_workstation_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hologram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='position',
        ),
        migrations.AlterField(
            model_name='project',
            name='tutorial',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='task',
            name='holograms',
            field=models.ManyToManyField(blank=True, to='website.hologram'),
        ),
    ]
