# Generated by Django 4.2.3 on 2023-07-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_hologram_remove_task_position_alter_project_tutorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hologram',
            name='url',
        ),
        migrations.AddField(
            model_name='hologram',
            name='obj',
            field=models.FileField(blank=True, null=True, upload_to='holograms/'),
        ),
    ]
