# Generated by Django 4.2.3 on 2023-07-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_hologram_url_hologram_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='description',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='qrcode',
        ),
    ]
