# Generated by Django 4.2.3 on 2023-07-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_priority_description_remove_priority_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='metadata',
        ),
        migrations.AddField(
            model_name='task',
            name='metadata_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.metadata'),
        ),
    ]
