# Generated by Django 4.2.3 on 2023-07-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_metadata_id_task_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='metadata',
        ),
        migrations.AddField(
            model_name='metadata',
            name='task_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.metadata'),
        ),
    ]
